# Generated by Django 5.1.2 on 2024-10-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucket_list', '0002_bucketlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketlist',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
