# Generated by Django 5.1.2 on 2024-10-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucket_list', '0003_alter_bucketlist_name'),
        ('explore', '0008_remove_food_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketlist',
            name='foods',
            field=models.ManyToManyField(related_name='bucket_lists', to='explore.food'),
        ),
    ]
