# Generated by Django 5.1.2 on 2024-10-26 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucket_list', '0003_alter_bucketlist_name'),
        ('explore', '0008_remove_food_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketlist',
            name='food_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='explore.food'),
            preserve_default=False,
        ),
    ]
