# Generated by Django 5.1.3 on 2024-12-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images/'),
        ),
    ]
