# Generated by Django 5.1.1 on 2024-10-14 13:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0004_remove_article_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="image",
            new_name="images",
        ),
    ]
