# Generated by Django 5.1.1 on 2024-10-14 13:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nama", models.CharField(max_length=255)),
                ("deskripsi", models.TextField()),
                ("harga", models.IntegerField()),
            ],
        ),
    ]
