# Generated by Django 5.1 on 2024-10-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_food_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image_link',
            field=models.URLField(default=''),
        ),
    ]
