# Generated by Django 5.1 on 2024-10-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0004_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.CharField(choices=[('Main Course', 'Main Course'), ('Dessert', 'Dessert'), ('Drinks', 'Drinks'), ('Snacks', 'Snacks')], default='Main Course', max_length=11),
        ),
    ]
