# Generated by Django 5.1.2 on 2024-10-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0008_remove_food_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='csvs')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
    ]
