# Generated by Django 5.1.2 on 2024-10-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('food_type', models.DateField(auto_now_add=True)),
                ('rating', models.TextField()),
                ('comments', models.IntegerField()),
            ],
        ),
    ]
