# Generated by Django 5.1.2 on 2024-10-20 11:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewentry',
            name='comments',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reviewentry',
            name='food_type',
            field=models.CharField(choices=[('MC', 'Main Course'), ('DS', 'Dessert'), ('DR', 'Drinks'), ('SN', 'Snacks')], max_length=2),
        ),
        migrations.AlterField(
            model_name='reviewentry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reviewentry',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
