# Generated by Django 5.1 on 2024-10-25 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0003_food_image_link'),
        ('food_review', '0002_alter_reviewentry_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewentry',
            name='food_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='explore.food'),
        ),
    ]
