# Generated by Django 5.1.2 on 2024-10-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_review', '0003_reviewentry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewentry',
            name='food_type',
            field=models.CharField(choices=[('Main Course', 'Main Course'), ('Dessert', 'Dessert'), ('Drinks', 'Drinks'), ('Snacks', 'Snacks')], max_length=50),
        ),
    ]
